global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'individuals-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'individuals-api:8080' ]

  - job_name: 'person-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'person-service:8082' ]

  - job_name: 'transaction-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'transaction-service:8083' ]