server:
  port: 8082

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: person-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: person-service
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: person
      org:
        hibernate:
          envers:
            default_schema: person
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/db
    user: person-service
    password: password
    schemas: person
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

otel:
  resource:
    attributes:
      service.name: person-service
  exporter:
    otlp:
      endpoint: http://localhost:4318
  logs:
    exporter: otlp
  metrics:
    exporter: otlp
  traces:
    exporter: otlp