version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=person-service
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U person-service" ]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.98.0
    command: [ "--config=/etc/otelcol/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      - loki
    networks:
      - observability-network

  loki:
    container_name: loki
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    networks:
      - observability-network

  grafana:
    container_name: grafana
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
    networks:
      - observability-network

networks:
  observability-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  grafana_data:
    driver: local