global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'person-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['otel-collector:9091']
        labels:
          application: 'person-service'