spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
keycloak:
  realm: my-realm
  auth-server-url: http://keycloak:8081
  resource: individuals-api
  credentials:
    secret: miwEW85QXAd55svjd2fIbJhvJEWaOpeD
  ssl-required: external
  public-client: false
  use-resource-role-mappings: true
  admin:
    client-id: admin-cli
    secret: 2abujMWRWo6INyJabgGVXzGcy7KgISwQ
    endpoint: /admin/realms/${keycloak.realm}
  endpoints:
    jwks: /realms/${keycloak.realm}/protocol/openid-connect/certs
    token: /realms/${keycloak.realm}/protocol/openid-connect/token
    userInfo: /realms/${keycloak.realm}/protocol/openid-connect/userinfo

management:
  port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    otlp:
      endpoint: http://alloy:4318
      protocol: http/protobuf

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

person-service:
  base-url: http://person-service:8082

transaction-service:
  base-url: http://transaction-service:8083/api/v1