server:
  port: 8083
spring:
  application:
    name: transaction-service
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8086
      specific.avro.reader: true
    consumer:
      group-id: transaction-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

SHARDS_CONFIG_PATH: shards_config-dev.json

kafka:
  topics:
    deposit-requested: deposit-requested
    withdrawal-requested: withdrawal-requested
    deposit-completed: deposit-completed
    withdrawal-completed: withdrawal-completed
    withdrawal-failed: withdrawal-failed

management:
  port: 8083
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html