server:
  port: 8083
spring:
  application:
    name: transaction-service
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: kafka:9093
    properties:
      schema.registry.url: http://schema-registry:8081
      specific.avro.reader: true
    consumer:
      group-id: transaction-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

shards:
  count: 2
  datasources:
    ds_0:
      jdbc-url: jdbc:postgresql://transaction-service-postgres-0:5432/transaction_db_0
      username: transaction-service
      password: password
    ds_1:
      jdbc-url: jdbc:postgresql://transaction-service-postgres-1:5432/transaction_db_1
      username: transaction-service
      password: password


kafka:
  topics:
    deposit-requested: deposit-requested
    withdrawal-requested: withdrawal-requested
    deposit-completed: deposit-completed
    withdrawal-completed: withdrawal-completed
    withdrawal-failed: withdrawal-failed

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

otel:
  resource:
    attributes:
      service.name: transaction-service
  exporter:
    otlp:
      endpoint: http://otel-collector:4318
  logs:
    exporter: otlp
  metrics:
    exporter: otlp
  traces:
    exporter: otlp