spring:
  application:
    name: transaction-service
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-dev.yml
  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8086
      specific.avro.reader: true
    consumer:
      group-id: transaction-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    deposit-requested: deposit-requested
    withdrawal-requested: withdrawal-requested
    deposit-completed: deposit-completed
    withdrawal-completed: withdrawal-completed
    withdrawal-failed: withdrawal-failed

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

otel:
  resource:
    attributes:
      service.name: transaction-service
  exporter:
    otlp:
      endpoint: http://localhost:4318
  logs:
    exporter: otlp
  metrics:
    exporter: otlp
  traces:
    exporter: otlp