spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://transaction-service-postgres:5432/db
    username: transaction-service
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://transaction-service-postgres:5432/db
    user: transaction-service
    password: password
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

otel:
  resource:
    attributes:
      service.name: transaction-service
  exporter:
    otlp:
      endpoint: http://localhost:4318
  logs:
    exporter: otlp
  metrics:
    exporter: otlp
  traces:
    exporter: otlp