openapi: 3.0.1
info:
  title: Person Service API
  version: 1.0.0
servers:
  - url: http://localhost:8081
paths:
  /api/v1/users/{id}:
    get:
      tags:
        - user-rest-controller-v-1
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorValidationResponse"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDto"
    put:
      tags:
        - user-rest-controller-v-1
      operationId: updateUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDto"
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorValidationResponse"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDto"
  /api/v1/users:
    post:
      tags:
        - user-rest-controller-v-1
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDto"
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorValidationResponse"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDto"
  /api/v1/countries:
    get:
      tags:
        - country-rest-controller-v-1
      operationId: getAllCountry
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorValidationResponse"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CountryDto"
    post:
      tags:
        - country-rest-controller-v-1
      operationId: createCountry
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CountryDto"
        required: true
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorValidationResponse"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "201":
          description: Created
  /api/v1/users/{id}/compensate:
    delete:
      tags:
        - user-rest-controller-v-1
      operationId: compensateCreateUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorValidationResponse"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: OK
components:
  schemas:
    ErrorValidationResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        errors:
          type: array
          items:
            $ref: "#/components/schemas/FieldErrorResponse"
    FieldErrorResponse:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        status:
          type: integer
          format: int32
    AddressDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        country:
          $ref: "#/components/schemas/CountryDto"
        address:
          type: string
        zip_code:
          type: string
        archived:
          type: string
          format: date-time
        city:
          type: string
        state:
          type: string
    CountryDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        alpha2:
          type: string
        alpha3:
          type: string
        status:
          type: string
    IndividualDto:
      type: object
      required:
        - verified_at
      properties:
        id:
          type: string
          format: uuid
        passport_number:
          type: string
        phone_number:
          type: string
        verified_at:
          type: string
          format: date-time
        archived_at:
          type: string
          format: date-time
        status:
          type: string
    UserDto:
      type: object
      required:
        - email
      properties:
        id:
          type: string
          format: uuid
        secret_key:
          type: string
        email:
          type: string
          pattern: '^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$'
          minLength: 1
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        first_name:
          type: string
        last_name:
          type: string
        filled:
          type: boolean
        address:
          $ref: "#/components/schemas/AddressDto"
        individual:
          $ref: "#/components/schemas/IndividualDto"
